chore: useDataQuery in TrackedEntityRelationshipTypeSelect
dhis2/maps-app pull request #2437
Opened 2023-01-12 10:47 UTC by jenniferarnesen

2023-01-15 21:00 UTC, turban requested changes

2023-01-16 08:24 UTC, jenniferarnesen commented on src/components/edit/trackedEntity/TrackedEntityRelationshipTypeSelect.js
>  import PropTypes from 'prop-types'
There are still other lodash functions used in other files so we can't remove lodash

2023-01-16 08:27 UTC, jenniferarnesen commented on src/components/edit/trackedEntity/TrackedEntityRelationshipTypeSelect.js
> +        return <span>{error}</span>
Right, sorry that was sloppy

2023-01-16 14:04 UTC, turban approved these changes
Nice refactor - easier to read than the original!

2023-01-16 14:12 UTC, merged